/**
 * Exact read-only AWS actions used by the checks (least privilege for the scanner role).
 * Keep in sync with packages/checks/src/aws and infra/aws-scanner-role.yaml (a unit test verifies this).
 * Note: iam:GenerateCredentialReport only (re)generates IAM's own credential report; it changes no configuration.
 */
export const AWS_SCANNER_ACTIONS = [
  'access-analyzer:ListAnalyzers',
  'backup:ListBackupPlans',
  'backup:ListBackupSelections',
  'backup:ListBackupVaults',
  'cloudtrail:DescribeTrails',
  'cloudtrail:GetEventSelectors',
  'cloudtrail:GetTrailStatus',
  'config:DescribeConfigurationRecorderStatus',
  'config:DescribeConfigurationRecorders',
  'config:DescribeDeliveryChannels',
  'ec2:DescribeFlowLogs',
  'ec2:DescribeImages',
  'ec2:DescribeInstances',
  'ec2:DescribeRegions',
  'ec2:DescribeSecurityGroups',
  'ec2:DescribeSnapshots',
  'ec2:DescribeVpcs',
  'ec2:GetEbsEncryptionByDefault',
  'guardduty:GetDetector',
  'guardduty:ListDetectors',
  'iam:GenerateCredentialReport',
  'iam:GetAccountAuthorizationDetails',
  'iam:GetAccountPasswordPolicy',
  'iam:GetAccountSummary',
  'iam:GetCredentialReport',
  'iam:ListVirtualMFADevices',
  'inspector2:BatchGetAccountStatus',
  'inspector2:ListFindings',
  'kms:DescribeKey',
  'kms:GetKeyRotationStatus',
  'kms:ListKeys',
  'rds:DescribeDBClusterSnapshotAttributes',
  'rds:DescribeDBClusterSnapshots',
  'rds:DescribeDBInstances',
  'rds:DescribeDBSnapshotAttributes',
  'rds:DescribeDBSnapshots',
  's3:GetAccountPublicAccessBlock',
  's3:GetBucketAcl',
  's3:GetBucketLocation',
  's3:GetBucketPolicy',
  's3:GetBucketPolicyStatus',
  's3:GetBucketPublicAccessBlock',
  's3:ListAllMyBuckets',
  'securityhub:DescribeHub',
  'securityhub:GetEnabledStandards',
  'securityhub:GetFindings',
] as const;
