import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const AWS = (d: Def): CheckMeta => ({ ...d, provider: 'aws' });

export const awsChecks: CheckMeta[] = [
  AWS({
    id: 'aws.root-mfa',
    domain: 'privileged',
    title: 'Root account protected with MFA',
    description: 'The AWS account root user has unrestricted access. It must be protected with multi-factor authentication (preferably a hardware key).',
    severity: 'critical',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Sign in as root, open Security credentials and assign an MFA device (FIDO2 security key recommended). Store the recovery procedure in a break-glass process.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/enable-mfa-for-root.html'],
    frameworks: { iso27001: ['8.5', '8.2'], cis: 'AWS CIS 1.5', nis2: 'Art. 21(2)(j)' },
  }),
  AWS({
    id: 'aws.root-access-keys',
    domain: 'privileged',
    title: 'No access keys for the root account',
    description: 'Programmatic access keys for the root user cannot be scoped down and are a high-value target.',
    severity: 'critical',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Delete all root access keys and use IAM roles with least privilege for automation.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user_manage_delete-key.html'],
    frameworks: { iso27001: ['8.2', '5.17'], cis: 'AWS CIS 1.4' },
  }),
  AWS({
    id: 'aws.iam-users-mfa',
    domain: 'identity',
    title: 'Console IAM users have MFA',
    description: 'IAM users with a console password but without MFA can be taken over with a single stolen password.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Enforce MFA for all console users, or better, move workforce access to IAM Identity Center federated with your IdP and remove IAM user passwords.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa.html'],
    frameworks: { iso27001: ['8.5', '5.17'], cis: 'AWS CIS 1.10', nis2: 'Art. 21(2)(j)' },
  }),
  AWS({
    id: 'aws.iam-access-key-age',
    domain: 'identity',
    title: 'Access keys rotated within 90 days',
    description: 'Long-lived access keys increase the window of opportunity when leaked (e.g. in source code).',
    severity: 'medium',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Rotate or remove access keys older than 90 days. Prefer IAM roles and short-lived credentials (OIDC federation for CI/CD).',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#rotating_access_keys_console'],
    frameworks: { iso27001: ['5.17'], cis: 'AWS CIS 1.14' },
  }),
  AWS({
    id: 'aws.iam-unused-credentials',
    domain: 'identity',
    title: 'No unused credentials (90+ days)',
    description: 'Passwords and access keys that have not been used for 90 days are likely orphaned and should be disabled.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Disable or delete credentials unused for 90 days and implement a joiner-mover-leaver review.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_finding-unused.html'],
    frameworks: { iso27001: ['5.18', '5.16'], cis: 'AWS CIS 1.12' },
  }),
  AWS({
    id: 'aws.password-policy',
    domain: 'identity',
    title: 'Strong IAM password policy',
    description: 'The account password policy should require at least 14 characters and prevent reuse.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Set an account password policy with minimum length 14 and password reuse prevention of 24.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_account-policy.html'],
    frameworks: { iso27001: ['5.17'], cis: 'AWS CIS 1.8' },
  }),
  AWS({
    id: 'aws.iam-admin-users',
    domain: 'privileged',
    title: 'No IAM users with direct AdministratorAccess',
    description: 'Full administrative permissions attached directly to IAM users are hard to govern and often permanent.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Remove AdministratorAccess from users. Grant admin through roles assumed just-in-time via IAM Identity Center permission sets.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html'],
    frameworks: { iso27001: ['8.2', '5.15'], cis: 'AWS CIS 1.16' },
  }),
  AWS({
    id: 'aws.cloudtrail',
    domain: 'logging',
    title: 'Multi-region CloudTrail with log validation',
    description: 'A multi-region trail that is logging and has log file validation enabled provides tamper-evident audit logging.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Create an organisation or multi-region trail, enable log file validation and deliver to a dedicated, locked-down S3 bucket (ideally in a log archive account).',
    references: ['https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-create-and-update-a-trail.html'],
    frameworks: { iso27001: ['8.15', '5.28'], cis: 'AWS CIS 3.1', nis2: 'Art. 21(2)(b)' },
  }),
  AWS({
    id: 'aws.guardduty',
    domain: 'logging',
    title: 'GuardDuty threat detection enabled',
    description: 'GuardDuty provides managed threat detection on CloudTrail, VPC flow and DNS logs.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable GuardDuty in all used regions (delegated administrator for organisations) and route findings to an alerting channel.',
    references: ['https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_settingup.html'],
    frameworks: { iso27001: ['8.16', '5.7'], nis2: 'Art. 21(2)(b)' },
  }),
  AWS({
    id: 'aws.securityhub',
    domain: 'governance',
    title: 'Security Hub enabled',
    description: 'Security Hub aggregates findings and continuously evaluates foundational best practices.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable Security Hub with the AWS Foundational Security Best Practices standard in all used regions.',
    references: ['https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-settingup.html'],
    frameworks: { iso27001: ['8.16', '8.9'] },
  }),
  AWS({
    id: 'aws.config',
    domain: 'governance',
    title: 'AWS Config recording enabled',
    description: 'AWS Config records configuration changes, which supports asset inventory, change tracking and investigations.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable AWS Config recorders in all used regions with global resource recording in one region.',
    references: ['https://docs.aws.amazon.com/config/latest/developerguide/gs-console.html'],
    frameworks: { iso27001: ['8.9', '5.9', '8.32'], cis: 'AWS CIS 3.3' },
  }),
  AWS({
    id: 'aws.s3-account-bpa',
    domain: 'data',
    title: 'Account-level S3 Block Public Access',
    description: 'Block Public Access at the account level prevents accidental public exposure of any bucket.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable all four S3 Block Public Access settings at the account level. Serve public content via CloudFront with Origin Access Control instead.',
    references: ['https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html'],
    frameworks: { iso27001: ['8.3', '8.12'], cis: 'AWS CIS 2.1.4' },
  }),
  AWS({
    id: 'aws.s3-public-buckets',
    domain: 'data',
    title: 'No publicly accessible S3 buckets',
    description: 'Buckets whose policy makes them public may expose sensitive data to anyone on the internet.',
    severity: 'critical',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Review each public bucket. Remove public statements from bucket policies and ACLs, enable bucket-level Block Public Access.',
    references: ['https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-policy-language-overview.html'],
    frameworks: { iso27001: ['8.3', '8.12', '5.34'] },
  }),
  AWS({
    id: 'aws.ebs-encryption',
    domain: 'data',
    title: 'EBS encryption by default',
    description: 'EBS encryption by default ensures new volumes and snapshots are encrypted at rest.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable "Always encrypt new EBS volumes" in every used region.',
    references: ['https://docs.aws.amazon.com/ebs/latest/userguide/encryption-by-default.html'],
    frameworks: { iso27001: ['8.24'], cis: 'AWS CIS 2.2.1' },
  }),
  AWS({
    id: 'aws.sg-admin-ports',
    domain: 'network',
    title: 'No admin ports open to the internet',
    description: 'Security groups allowing SSH, RDP or database ports from 0.0.0.0/0 or ::/0 are a common initial access vector.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Restrict ingress to known IP ranges, or remove it and use SSM Session Manager or a VPN / zero-trust access instead.',
    references: ['https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html'],
    frameworks: { iso27001: ['8.20', '8.22'], cis: 'AWS CIS 5.2', nis2: 'Art. 21(2)(e)' },
  }),
  AWS({
    id: 'aws.ec2-imdsv2',
    domain: 'network',
    title: 'EC2 instances require IMDSv2',
    description: 'IMDSv1 is susceptible to SSRF-based credential theft. IMDSv2 requires session tokens.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'medium',
    remediation: 'Set HttpTokens=required on instances and launch templates; set the account default to IMDSv2.',
    references: ['https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html'],
    frameworks: { iso27001: ['8.9'], cis: 'AWS CIS 5.6' },
  }),
  AWS({
    id: 'aws.rds-public',
    domain: 'network',
    title: 'No publicly accessible RDS instances',
    description: 'Databases reachable from the internet are exposed to brute force and exploitation.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Set PubliclyAccessible=false and place databases in private subnets.',
    references: ['https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html'],
    frameworks: { iso27001: ['8.20', '8.3'] },
  }),
  AWS({
    id: 'aws.rds-encryption',
    domain: 'data',
    title: 'RDS storage encrypted',
    description: 'Database storage should be encrypted at rest with KMS.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'high',
    remediation: 'Encrypted storage cannot be enabled in place: restore an encrypted snapshot copy into a new instance.',
    references: ['https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html'],
    frameworks: { iso27001: ['8.24'], cis: 'AWS CIS 2.3.1' },
  }),
  AWS({
    id: 'aws.rds-backup',
    domain: 'data',
    title: 'RDS automated backups retained 7+ days',
    description: 'Automated backups with sufficient retention allow point-in-time recovery after ransomware or operator errors.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Set backup retention to at least 7 days and consider AWS Backup with vault lock for immutable copies.',
    references: ['https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html'],
    frameworks: { iso27001: ['8.13'], nis2: 'Art. 21(2)(c)' },
  }),
  AWS({
    id: 'aws.kms-rotation',
    domain: 'data',
    title: 'Customer managed KMS keys rotated',
    description: 'Automatic key rotation limits the amount of data protected by a single key version.',
    severity: 'low',
    minRisk: 'high',
    effort: 'low',
    remediation: 'Enable automatic rotation on symmetric customer managed keys.',
    references: ['https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html'],
    frameworks: { iso27001: ['8.24'], cis: 'AWS CIS 3.6' },
  }),
  AWS({
    id: 'aws.access-analyzer',
    domain: 'governance',
    title: 'IAM Access Analyzer enabled',
    description: 'Access Analyzer identifies resources shared with external principals.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Create an account or organisation analyzer in each used region and review its findings.',
    references: ['https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html'],
    frameworks: { iso27001: ['5.18', '5.19'], cis: 'AWS CIS 1.20' },
  }),
];
