import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const AZ = (d: Def): CheckMeta => ({ ...d, provider: 'azure' });

/** CIS references use the CIS Microsoft Azure Foundations Benchmark v3.0.0 numbering. */
export const azureChecks: CheckMeta[] = [
  AZ({
    id: 'azure.defender-plans',
    domain: 'logging',
    title: 'Microsoft Defender for Cloud plans enabled',
    description:
      'Defender plans provide threat detection and vulnerability assessment. Resource Manager and Defender CSPM are expected on every subscription; Servers, Storage, Key Vault, SQL, App Service, Containers, open-source relational databases and Cosmos DB plans are expected when such resources are deployed.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable the Defender plans matching deployed workloads (Defender for Cloud > Environment settings > subscription > Defender plans), plus Resource Manager and Defender CSPM.',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/connect-azure-subscription'],
    frameworks: { iso27001: ['8.16'], cis: 'Azure CIS v3.0 2.1.1-2.1.13' },
  }),
  AZ({
    id: 'azure.security-contact',
    domain: 'logging',
    title: 'Security contact configured',
    description: 'Defender for Cloud needs a security contact to notify about high severity alerts.',
    severity: 'low',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Configure security contact e-mail addresses and alert notifications for high severity in Defender for Cloud environment settings.',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/configure-email-notifications'],
    frameworks: { iso27001: ['5.24', '5.25'], cis: 'Azure CIS v3.0 2.1.19, 2.1.20' },
  }),
  AZ({
    id: 'azure.activity-log-export',
    domain: 'logging',
    title: 'Activity log exported',
    description:
      'Subscription activity logs are only kept 90 days unless exported. A diagnostic setting with a destination must export at least the Administrative, Alert, Policy and Security categories.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Create a subscription diagnostic setting exporting all activity log categories (or the allLogs group) to a Log Analytics workspace (or Sentinel).',
    references: ['https://learn.microsoft.com/azure/azure-monitor/essentials/diagnostic-settings'],
    frameworks: { iso27001: ['8.15'], cis: 'Azure CIS v3.0 5.1.1, 5.1.2' },
  }),
  AZ({
    id: 'azure.storage-public',
    domain: 'data',
    title: 'Storage accounts disallow public blob access',
    description: 'Storage accounts that allow anonymous blob access can leak data through misconfigured containers.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Set allowBlobPublicAccess=false on all storage accounts (enforce with Azure Policy).',
    references: ['https://learn.microsoft.com/azure/storage/blobs/anonymous-read-access-prevent'],
    frameworks: { iso27001: ['8.3'], cis: 'Azure CIS v3.0 3.17' },
  }),
  AZ({
    id: 'azure.storage-transport',
    domain: 'data',
    title: 'Storage enforces HTTPS and TLS 1.2+',
    description: 'Storage accounts must explicitly require secure transfer (supportsHttpsTrafficOnly) and a minimum TLS version of 1.2 or higher; a missing setting counts as not enforced.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable "Secure transfer required" and set minimum TLS version to 1.2.',
    references: ['https://learn.microsoft.com/azure/storage/common/transport-layer-security-configure-minimum-version'],
    frameworks: { iso27001: ['8.24'], cis: 'Azure CIS v3.0 3.1, 3.15' },
  }),
  AZ({
    id: 'azure.storage-network',
    domain: 'network',
    title: 'Storage network access restricted',
    description:
      'Storage accounts should not be reachable from all networks (public network access with default action Allow), should disable shared key access in favour of Entra ID authorisation, and should keep blob soft delete on.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Set the network default action to Deny (or disable public network access and use private endpoints), set allowSharedKeyAccess=false after moving clients to Entra ID, and enable blob soft delete.',
    references: ['https://learn.microsoft.com/azure/storage/common/storage-network-security', 'https://learn.microsoft.com/azure/storage/common/shared-key-authorization-prevent'],
    frameworks: { iso27001: ['8.20', '8.3'], cis: 'Azure CIS v3.0 3.7, 3.8, 3.11' },
  }),
  AZ({
    id: 'azure.keyvault-protection',
    domain: 'data',
    title: 'Key Vault soft delete, purge protection and RBAC',
    description: 'Soft delete and purge protection prevent permanent deletion of keys and secrets during the retention period (ransomware resilience); RBAC authorization replaces vault access policies.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable soft delete and purge protection on every Key Vault and switch the permission model to Azure role-based access control.',
    references: ['https://learn.microsoft.com/azure/key-vault/general/soft-delete-overview', 'https://learn.microsoft.com/azure/key-vault/general/rbac-migration'],
    frameworks: { iso27001: ['8.24'], cis: 'Azure CIS v3.0 8.5, 8.6' },
  }),
  AZ({
    id: 'azure.nsg-admin-ports',
    domain: 'network',
    title: 'No management or database ports open to the internet',
    description:
      'NSG rules allowing administrative or database ports (SSH, RDP, Telnet, FTP, SMB, WinRM, SQL Server, Oracle, MySQL, PostgreSQL, MongoDB, Redis, Elasticsearch) from any source, the Internet tag or prefixes of /8 or wider are actively scanned and brute-forced. Rule priority is honoured: a higher-priority Deny from any source protects the port.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Remove internet-facing management rules; use Azure Bastion, just-in-time VM access or private endpoints.',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/just-in-time-access-overview'],
    frameworks: { iso27001: ['8.20'], cis: 'Azure CIS v3.0 6.1, 6.2' },
  }),
  AZ({
    id: 'azure.sql-public',
    domain: 'network',
    title: 'SQL servers not open to the internet',
    description: 'Firewall rules allowing 0.0.0.0-255.255.255.255 or other very broad ranges (/8 or wider) expose databases to the internet; "Allow Azure services" admits traffic from any Azure tenant.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Remove broad firewall rules, disable public network access and use private endpoints.',
    references: ['https://learn.microsoft.com/azure/azure-sql/database/firewall-configure'],
    frameworks: { iso27001: ['8.20', '8.3'], cis: 'Azure CIS v3.0 4.1.2' },
  }),
  AZ({
    id: 'azure.sql-auditing-tde',
    domain: 'logging',
    title: 'SQL auditing, TDE and Entra admin',
    description: 'Azure SQL servers should have auditing enabled, transparent data encryption on every database and a Microsoft Entra administrator so access is tied to managed identities.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable server auditing to Log Analytics or storage, enable TDE on every database and configure a Microsoft Entra admin (group) on each server.',
    references: ['https://learn.microsoft.com/azure/azure-sql/database/auditing-overview', 'https://learn.microsoft.com/azure/azure-sql/database/transparent-data-encryption-tde-overview'],
    frameworks: { iso27001: ['8.15', '8.24'], cis: 'Azure CIS v3.0 4.1.1, 4.1.4, 4.1.5' },
  }),
  AZ({
    id: 'azure.defender-recommendations',
    domain: 'governance',
    title: 'No unhealthy high-severity Defender recommendations',
    description: 'Defender for Cloud assessments flag vulnerable or misconfigured resources. Unhealthy high-severity recommendations are known, unremediated weaknesses.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Work through the high-severity recommendations in Defender for Cloud > Recommendations, remediate or exempt them with a documented reason.',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/review-security-recommendations'],
    frameworks: { iso27001: ['8.8', '8.9'] },
  }),
  AZ({
    id: 'azure.backup-vaults',
    domain: 'data',
    title: 'Backup vaults protected against deletion',
    description: 'Recovery Services and Backup vaults should keep soft delete enabled and use immutability so an attacker with access cannot delete or alter backups.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable soft delete (preferably always-on) and immutability (lock it once validated) on every Recovery Services and Backup vault.',
    references: ['https://learn.microsoft.com/azure/backup/backup-azure-immutable-vault-concept', 'https://learn.microsoft.com/azure/backup/backup-azure-security-feature-cloud'],
    frameworks: { iso27001: ['8.13'] },
  }),
  AZ({
    id: 'azure.subscription-owners',
    domain: 'privileged',
    title: 'Limited subscription Owners',
    description:
      'Owner and User Access Administrator on a subscription grant control over access management. Keep at least 2 Owners (no single point of failure) and at most 3 Owner or User Access Administrator principals; groups are counted as one principal and listed so their membership can be reviewed.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Keep 2 or 3 named Owners per subscription, remove other Owner and User Access Administrator assignments and use PIM eligible assignments for the rest.',
    references: ['https://learn.microsoft.com/azure/role-based-access-control/best-practices'],
    frameworks: { iso27001: ['8.2', '5.18'] },
  }),
];
