import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const AZ = (d: Def): CheckMeta => ({ ...d, provider: 'azure' });

export const azureChecks: CheckMeta[] = [
  AZ({
    id: 'azure.defender-plans',
    domain: 'logging',
    title: 'Microsoft Defender for Cloud plans enabled',
    description: 'Defender plans for servers, storage, key vault and databases provide threat detection and vulnerability assessment.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable the Defender plans matching deployed workloads (at least Servers, Storage, Key Vault, Resource Manager).',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/connect-azure-subscription'],
    frameworks: { iso27001: ['8.16', '8.7', '8.8'], cis: 'Azure CIS 3.1' },
  }),
  AZ({
    id: 'azure.security-contact',
    domain: 'governance',
    title: 'Security contact configured',
    description: 'Defender for Cloud needs a security contact to notify about high severity alerts.',
    severity: 'low',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Configure security contact e-mail addresses and alert notifications for high severity in Defender for Cloud environment settings.',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/configure-email-notifications'],
    frameworks: { iso27001: ['5.24', '5.25'], cis: 'Azure CIS 3.1.13' },
  }),
  AZ({
    id: 'azure.activity-log-export',
    domain: 'logging',
    title: 'Activity log exported',
    description: 'Subscription activity logs are only kept 90 days unless exported to Log Analytics or storage.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Create a subscription diagnostic setting exporting all activity log categories to a Log Analytics workspace (or Sentinel).',
    references: ['https://learn.microsoft.com/azure/azure-monitor/essentials/diagnostic-settings'],
    frameworks: { iso27001: ['8.15', '5.28'], cis: 'Azure CIS 5.1.1' },
  }),
  AZ({
    id: 'azure.storage-public',
    domain: 'data',
    title: 'Storage accounts disallow public blob access',
    description: 'Storage accounts that allow anonymous blob access can leak data through misconfigured containers.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Set allowBlobPublicAccess=false on all storage accounts (enforce with Azure Policy).',
    references: ['https://learn.microsoft.com/azure/storage/blobs/anonymous-read-access-prevent'],
    frameworks: { iso27001: ['8.3', '8.12'], cis: 'Azure CIS 4.7' },
  }),
  AZ({
    id: 'azure.storage-transport',
    domain: 'data',
    title: 'Storage enforces HTTPS and TLS 1.2+',
    description: 'Storage accounts should reject plain HTTP and legacy TLS versions.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable "Secure transfer required" and set minimum TLS version to 1.2.',
    references: ['https://learn.microsoft.com/azure/storage/common/transport-layer-security-configure-minimum-version'],
    frameworks: { iso27001: ['8.24'], cis: 'Azure CIS 4.1' },
  }),
  AZ({
    id: 'azure.keyvault-protection',
    domain: 'data',
    title: 'Key Vault purge protection enabled',
    description: 'Purge protection prevents permanent deletion of keys and secrets during the retention period (ransomware resilience).',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable soft delete and purge protection on every Key Vault.',
    references: ['https://learn.microsoft.com/azure/key-vault/general/soft-delete-overview'],
    frameworks: { iso27001: ['8.24', '8.13'], cis: 'Azure CIS 8.5' },
  }),
  AZ({
    id: 'azure.nsg-admin-ports',
    domain: 'network',
    title: 'No management ports open to the internet',
    description: 'NSG rules allowing RDP/SSH from any source are actively scanned and brute-forced.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Remove internet-facing management rules; use Azure Bastion or just-in-time VM access.',
    references: ['https://learn.microsoft.com/azure/defender-for-cloud/just-in-time-access-overview'],
    frameworks: { iso27001: ['8.20', '8.22'], cis: 'Azure CIS 6.1' },
  }),
  AZ({
    id: 'azure.sql-public',
    domain: 'network',
    title: 'SQL servers not open to all IPs',
    description: 'Firewall rules allowing 0.0.0.0-255.255.255.255 expose databases to the whole internet.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Remove broad firewall rules, disable public network access and use private endpoints.',
    references: ['https://learn.microsoft.com/azure/azure-sql/database/firewall-configure'],
    frameworks: { iso27001: ['8.20', '8.3'], cis: 'Azure CIS 6.3' },
  }),
  AZ({
    id: 'azure.subscription-owners',
    domain: 'privileged',
    title: 'Limited subscription Owners',
    description: 'Owner on a subscription grants full control including access management. Keep it to a few named people or groups.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Reduce Owner assignments to at most 3 and use PIM eligible assignments for the rest.',
    references: ['https://learn.microsoft.com/azure/role-based-access-control/best-practices'],
    frameworks: { iso27001: ['8.2', '5.18'], cis: 'Azure CIS 1.23' },
  }),
];
