import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const GH = (d: Def): CheckMeta => ({ ...d, provider: 'github' });

export const githubChecks: CheckMeta[] = [
  GH({
    id: 'gh.org-2fa',
    domain: 'identity',
    title: 'Organisation requires 2FA',
    description: 'Requiring two-factor authentication for all members and outside collaborators protects against credential stuffing.',
    severity: 'critical',
    effort: 'low',
    remediation: 'Enable "Require two-factor authentication" in organisation Authentication security settings (or enforce SSO via your IdP with MFA).',
    references: ['https://docs.github.com/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization'],
    frameworks: { iso27001: ['8.5', '8.4'], cis: 'GitHub CIS 1.3.5', nis2: 'Art. 21(2)(j)' },
  }),
  GH({
    id: 'gh.base-permissions',
    domain: 'identity',
    title: 'Least-privilege base permissions',
    description: 'Base permission write/admin gives every member write access to every repository.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Set base permissions to "Read" or "No permission" and grant write access through teams.',
    references: ['https://docs.github.com/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/setting-base-permissions-for-an-organization'],
    frameworks: { iso27001: ['8.4', '5.15'], cis: 'GitHub CIS 1.3.8' },
  }),
  GH({
    id: 'gh.owner-count',
    domain: 'privileged',
    title: 'Limited organisation owners',
    description: 'Organisation owners have full control. Keep the number small, but have at least two to avoid lock-out.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Reduce owners to 2-4 people and use the security manager or custom roles for delegated duties.',
    references: ['https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization'],
    frameworks: { iso27001: ['8.2'], cis: 'GitHub CIS 1.3.3' },
  }),
  GH({
    id: 'gh.outside-collaborators',
    domain: 'identity',
    title: 'Outside collaborators reviewed',
    description:
      'Outside collaborators are not covered by organisation membership policies and are easily forgotten. Each one is reported with the highest repository permission found: write, maintain or admin fails, read or triage warns.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Review outside collaborators, remove those no longer needed and reduce write or admin access to read where possible. Prefer bringing contractors in as members with SSO.',
    references: ['https://docs.github.com/organizations/managing-user-access-to-your-organizations-repositories/managing-outside-collaborators'],
    frameworks: { iso27001: ['5.19', '5.18'] },
  }),
  GH({
    id: 'gh.public-repo-creation',
    domain: 'data',
    title: 'Members cannot create public repositories',
    description: 'Allowing members to create public repositories risks accidental publication of code or secrets.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Restrict repository creation to private/internal for members.',
    references: ['https://docs.github.com/organizations/managing-organization-settings/restricting-repository-creation-in-your-organization'],
    frameworks: { iso27001: ['8.12', '8.4'], cis: 'GitHub CIS 1.2.2' },
  }),
  GH({
    id: 'gh.private-forking',
    domain: 'data',
    title: 'Private repository forking restricted',
    description: 'Forks of private repositories can end up in personal accounts, outside of organisation control.',
    severity: 'low',
    effort: 'low',
    remediation: 'Disable "Allow forking of private repositories" unless needed.',
    references: ['https://docs.github.com/organizations/managing-organization-settings/managing-the-forking-policy-for-your-organization'],
    frameworks: { iso27001: ['8.12'] },
  }),
  GH({
    id: 'gh.public-repos',
    domain: 'data',
    title: 'Public repositories reviewed',
    description: 'Lists public repositories so the owners can confirm each is intentionally public.',
    severity: 'info',
    effort: 'low',
    remediation: 'Confirm each public repository is intended to be public; archive or make private otherwise.',
    references: ['https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility'],
    frameworks: { iso27001: ['8.12'] },
  }),
  GH({
    id: 'gh.branch-protection',
    domain: 'supply_chain',
    title: 'Default branches protected',
    description:
      'Branch protection or active rulesets on default branches must require at least one approving review, dismiss stale approvals, apply to administrators (enforce admins, or no ruleset bypass actors), and block force pushes and deletion. No protection fails; partial protection warns with the missing parts. Rulesets in evaluate mode do not count.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Create an active organisation ruleset for default branches requiring pull requests with at least one approval and stale review dismissal, blocking force pushes and deletion, without bypass actors (or enable "Do not allow bypassing" in classic branch protection).',
    references: ['https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets'],
    frameworks: { iso27001: ['8.32', '8.25', '8.4'], cis: 'GitHub CIS 1.1.3, 1.1.4, 1.1.14, 1.1.16, 1.1.17' },
  }),
  GH({
    id: 'gh.secret-scanning',
    domain: 'supply_chain',
    title: 'Secret scanning enabled',
    description: 'Secret scanning detects credentials committed to repositories.',
    severity: 'high',
    effort: 'low',
    remediation: 'Enable secret scanning on all repositories (free for public; GitHub Secret Protection for private).',
    references: ['https://docs.github.com/code-security/secret-scanning/enabling-secret-scanning-features'],
    frameworks: { iso27001: ['8.28', '5.17'], cis: 'GitHub CIS 1.5.1' },
  }),
  GH({
    id: 'gh.push-protection',
    domain: 'supply_chain',
    title: 'Secret push protection enabled',
    description: 'Push protection blocks secrets before they reach the repository.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Enable push protection together with secret scanning.',
    references: ['https://docs.github.com/code-security/secret-scanning/introduction/about-push-protection'],
    frameworks: { iso27001: ['8.28', '5.17'], cis: 'GitHub CIS 1.5.1' },
  }),
  GH({
    id: 'gh.secret-scanning-alerts',
    domain: 'supply_chain',
    title: 'No open secret scanning alerts',
    description:
      'Open secret scanning alerts are credentials (cloud keys, tokens, passwords) that were committed to a repository and are still marked unresolved. Anyone with read access to the repository or its history can use them.',
    severity: 'critical',
    effort: 'medium',
    remediation: 'Rotate or revoke each exposed credential first, then close the alert as revoked. Removing the commit alone is not enough because the secret stays in history and forks.',
    references: ['https://docs.github.com/code-security/secret-scanning/managing-alerts-from-secret-scanning/about-alerts'],
    frameworks: { iso27001: ['8.28', '5.17'], cis: 'GitHub CIS 1.5.1' },
    requires: 'Secret scanning alerts: read',
  }),
  GH({
    id: 'gh.dependabot-alerts',
    domain: 'supply_chain',
    title: 'No open critical/high Dependabot alerts',
    description:
      'Dependabot alerts must be enabled on every repository, and open alerts of critical or high severity indicate unpatched known vulnerabilities. Not enabled on any repository fails; partial coverage warns. Repositories with alerts but without Dependabot security updates (automatic fix pull requests) are also reported.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Enable Dependabot alerts and security updates on all repositories (organisation code security configuration), triage and fix open critical and high alerts; set an SLA for remediation.',
    references: ['https://docs.github.com/code-security/dependabot/dependabot-alerts/about-dependabot-alerts'],
    frameworks: { iso27001: ['8.8', '5.21', '8.25'], cis: 'GitHub CIS 1.5.5', nis2: 'Art. 21(2)(e)' },
  }),
  GH({
    id: 'gh.code-scanning-alerts',
    domain: 'supply_chain',
    title: 'No open critical/high code scanning alerts',
    description:
      'Code scanning should run on every repository, and open static analysis alerts of high severity point to exploitable flaws in in-house code. A repository counts as covered only when an analysis ran in the last 90 days. Not set up on any repository fails; partial coverage warns.',
    severity: 'medium',
    effort: 'high',
    remediation: 'Enable CodeQL default setup on all repositories and remediate critical and high alerts.',
    references: ['https://docs.github.com/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning'],
    frameworks: { iso27001: ['8.28', '8.8'], cis: 'GitHub CIS 1.5.4' },
  }),
  GH({
    id: 'gh.actions-allowed',
    domain: 'supply_chain',
    title: 'GitHub Actions restricted to trusted actions',
    description:
      'Allowing all actions lets any third-party action run with access to repository secrets. A "selected" policy with a wildcard pattern such as "*" counts as allowing all actions.',
    severity: 'medium',
    effort: 'medium',
    remediation: 'Allow only GitHub-authored, verified-creator and explicitly listed actions; pin third-party actions to a commit SHA.',
    references: ['https://docs.github.com/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization'],
    frameworks: { iso27001: ['5.21', '8.25'] },
  }),
  GH({
    id: 'gh.workflow-permissions',
    domain: 'supply_chain',
    title: 'Read-only default workflow token',
    description: 'A default GITHUB_TOKEN with write permissions amplifies the impact of a compromised workflow.',
    severity: 'high',
    effort: 'low',
    remediation: 'Set default workflow permissions to "Read repository contents" and disallow Actions from approving pull requests.',
    references: ['https://docs.github.com/actions/security-for-github-actions/security-guides/automatic-token-authentication'],
    frameworks: { iso27001: ['8.25', '8.2'] },
  }),
  GH({
    id: 'gh.deploy-keys',
    domain: 'supply_chain',
    title: 'Deploy keys are read-only',
    description: 'Write-enabled deploy keys are long-lived credentials that can push code.',
    severity: 'low',
    effort: 'low',
    remediation: 'Replace write deploy keys with GitHub Apps or fine-grained tokens with expiry.',
    references: ['https://docs.github.com/authentication/connecting-to-github-with-ssh/managing-deploy-keys'],
    frameworks: { iso27001: ['5.17', '8.4'] },
  }),
  GH({
    id: 'gh.webhooks',
    domain: 'network',
    title: 'Webhooks use verified HTTPS',
    description: 'Webhooks over plain HTTP or with SSL verification disabled can leak payloads.',
    severity: 'low',
    effort: 'low',
    remediation: 'Use HTTPS webhook URLs with SSL verification and a secret.',
    references: ['https://docs.github.com/webhooks/using-webhooks/best-practices-for-using-webhooks'],
    frameworks: { iso27001: ['8.21', '8.24'] },
  }),
  GH({
    id: 'gh.members-without-2fa',
    domain: 'identity',
    title: 'No members without 2FA',
    description:
      'When the organisation does not enforce two-factor authentication, lists members and outside collaborators who have not enabled it. Passes when 2FA is enforced. The 2FA filter is only available to organisation owners.',
    severity: 'high',
    effort: 'low',
    remediation: 'Ask the listed accounts to enable 2FA (preferably passkeys or a security key), then enforce "Require two-factor authentication" for the organisation.',
    references: ['https://docs.github.com/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/viewing-whether-users-in-your-organization-have-2fa-enabled'],
    frameworks: { iso27001: ['8.5'], cis: 'GitHub CIS 1.3.4', nis2: 'Art. 21(2)(j)' },
    requires: 'Organisation owner token',
  }),
  GH({
    id: 'gh.app-installations',
    domain: 'supply_chain',
    title: 'GitHub Apps hold least privilege',
    description:
      'GitHub Apps installed on the organisation act with their own permissions. Write access to administration, members, contents, workflows, secrets or actions lets a compromised vendor change code, CI or access. Organisation administration or members write fails; other broad write permissions warn.',
    severity: 'medium',
    effort: 'medium',
    remediation: 'Review installed GitHub Apps, uninstall unused ones, limit them to selected repositories and reject permission upgrades that are not needed.',
    references: ['https://docs.github.com/apps/using-github-apps/reviewing-and-modifying-installed-github-apps'],
    frameworks: { iso27001: ['5.21', '5.19'], cis: 'GitHub CIS 1.4.3' },
    requires: 'Organisation Administration: read',
  }),
  GH({
    id: 'gh.security-defaults',
    domain: 'supply_chain',
    title: 'Security features on by default for new repositories',
    description:
      'New repositories should automatically get the dependency graph, Dependabot alerts and security updates, secret scanning and push protection, either through the organisation defaults or a default code security configuration.',
    severity: 'low',
    effort: 'low',
    remediation: 'Apply a code security configuration as the default for all new repositories (Organisation settings, Code security, Configurations) with these features enabled.',
    references: ['https://docs.github.com/code-security/securing-your-organization/enabling-security-features-in-your-organization/applying-a-custom-security-configuration'],
    frameworks: { iso27001: ['8.9', '8.25'] },
  }),
];
