import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const GH = (d: Def): CheckMeta => ({ ...d, provider: 'github' });

export const githubChecks: CheckMeta[] = [
  GH({
    id: 'gh.org-2fa',
    domain: 'identity',
    title: 'Organisation requires 2FA',
    description: 'Requiring two-factor authentication for all members and outside collaborators protects against credential stuffing.',
    severity: 'critical',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable "Require two-factor authentication" in organisation Authentication security settings (or enforce SSO via your IdP with MFA).',
    references: ['https://docs.github.com/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization'],
    frameworks: { iso27001: ['8.5', '8.4'], nis2: 'Art. 21(2)(j)' },
  }),
  GH({
    id: 'gh.base-permissions',
    domain: 'identity',
    title: 'Least-privilege base permissions',
    description: 'Base permission write/admin gives every member write access to every repository.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Set base permissions to "Read" or "No permission" and grant write access through teams.',
    references: ['https://docs.github.com/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/setting-base-permissions-for-an-organization'],
    frameworks: { iso27001: ['8.4', '5.15'] },
  }),
  GH({
    id: 'gh.owner-count',
    domain: 'privileged',
    title: 'Limited organisation owners',
    description: 'Organisation owners have full control. Keep the number small.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Reduce owners to 2-4 people and use the security manager or custom roles for delegated duties.',
    references: ['https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization'],
    frameworks: { iso27001: ['8.2'] },
  }),
  GH({
    id: 'gh.outside-collaborators',
    domain: 'identity',
    title: 'Outside collaborators reviewed',
    description: 'Outside collaborators are not covered by organisation membership policies and are easily forgotten.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Review outside collaborators and remove those no longer needed. Prefer bringing contractors in as members with SSO.',
    references: ['https://docs.github.com/organizations/managing-user-access-to-your-organizations-repositories/managing-outside-collaborators'],
    frameworks: { iso27001: ['5.19', '5.18'] },
  }),
  GH({
    id: 'gh.public-repo-creation',
    domain: 'data',
    title: 'Members cannot create public repositories',
    description: 'Allowing members to create public repositories risks accidental publication of code or secrets.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Restrict repository creation to private/internal for members.',
    references: ['https://docs.github.com/organizations/managing-organization-settings/restricting-repository-creation-in-your-organization'],
    frameworks: { iso27001: ['8.12', '8.4'] },
  }),
  GH({
    id: 'gh.private-forking',
    domain: 'data',
    title: 'Private repository forking restricted',
    description: 'Forks of private repositories can end up in personal accounts, outside of organisation control.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Disable "Allow forking of private repositories" unless needed.',
    references: ['https://docs.github.com/organizations/managing-organization-settings/managing-the-forking-policy-for-your-organization'],
    frameworks: { iso27001: ['8.12'] },
  }),
  GH({
    id: 'gh.public-repos',
    domain: 'data',
    title: 'Public repositories reviewed',
    description: 'Lists public repositories so the customer can confirm each is intentionally public.',
    severity: 'info',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Confirm each public repository is intended to be public; archive or make private otherwise.',
    references: ['https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility'],
    frameworks: { iso27001: ['5.9', '8.12'] },
  }),
  GH({
    id: 'gh.branch-protection',
    domain: 'supply_chain',
    title: 'Default branches protected',
    description: 'Branch protection or rulesets on default branches enforce reviews and prevent force pushes.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Create an organisation ruleset for default branches requiring pull requests with at least one approval and blocking force pushes and deletion.',
    references: ['https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets'],
    frameworks: { iso27001: ['8.32', '8.25', '8.4'] },
  }),
  GH({
    id: 'gh.secret-scanning',
    domain: 'supply_chain',
    title: 'Secret scanning enabled',
    description: 'Secret scanning detects credentials committed to repositories.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Enable secret scanning on all repositories (free for public; GitHub Secret Protection for private).',
    references: ['https://docs.github.com/code-security/secret-scanning/enabling-secret-scanning-features'],
    frameworks: { iso27001: ['8.28', '5.17'] },
  }),
  GH({
    id: 'gh.push-protection',
    domain: 'supply_chain',
    title: 'Secret push protection enabled',
    description: 'Push protection blocks secrets before they reach the repository.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Enable push protection together with secret scanning.',
    references: ['https://docs.github.com/code-security/secret-scanning/introduction/about-push-protection'],
    frameworks: { iso27001: ['8.28', '5.17'] },
  }),
  GH({
    id: 'gh.dependabot-alerts',
    domain: 'supply_chain',
    title: 'No open critical/high Dependabot alerts',
    description: 'Open vulnerable dependency alerts of critical or high severity indicate unpatched known vulnerabilities.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Enable Dependabot security updates, triage and fix open critical and high alerts; set an SLA for remediation.',
    references: ['https://docs.github.com/code-security/dependabot/dependabot-alerts/about-dependabot-alerts'],
    frameworks: { iso27001: ['8.8', '8.25'], nis2: 'Art. 21(2)(e)' },
  }),
  GH({
    id: 'gh.code-scanning-alerts',
    domain: 'supply_chain',
    title: 'No open critical/high code scanning alerts',
    description: 'Open static analysis alerts of high severity point to exploitable flaws in in-house code.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'high',
    remediation: 'Enable CodeQL default setup and remediate critical and high alerts.',
    references: ['https://docs.github.com/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning'],
    frameworks: { iso27001: ['8.28', '8.8'] },
  }),
  GH({
    id: 'gh.actions-allowed',
    domain: 'supply_chain',
    title: 'GitHub Actions restricted to trusted actions',
    description: 'Allowing all actions lets any third-party action run with access to repository secrets.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Allow only GitHub-authored, verified-creator and explicitly listed actions; pin third-party actions to a commit SHA.',
    references: ['https://docs.github.com/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization'],
    frameworks: { iso27001: ['5.19', '8.25'] },
  }),
  GH({
    id: 'gh.workflow-permissions',
    domain: 'supply_chain',
    title: 'Read-only default workflow token',
    description: 'A default GITHUB_TOKEN with write permissions amplifies the impact of a compromised workflow.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Set default workflow permissions to "Read repository contents" and disallow Actions from approving pull requests.',
    references: ['https://docs.github.com/actions/security-for-github-actions/security-guides/automatic-token-authentication'],
    frameworks: { iso27001: ['8.25', '8.2'] },
  }),
  GH({
    id: 'gh.deploy-keys',
    domain: 'supply_chain',
    title: 'Deploy keys are read-only',
    description: 'Write-enabled deploy keys are long-lived credentials that can push code.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Replace write deploy keys with GitHub Apps or fine-grained tokens with expiry.',
    references: ['https://docs.github.com/authentication/connecting-to-github-with-ssh/managing-deploy-keys'],
    frameworks: { iso27001: ['5.17', '8.4'] },
  }),
  GH({
    id: 'gh.webhooks',
    domain: 'network',
    title: 'Webhooks use verified HTTPS',
    description: 'Webhooks over plain HTTP or with SSL verification disabled can leak payloads.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Use HTTPS webhook URLs with SSL verification and a secret.',
    references: ['https://docs.github.com/webhooks/using-webhooks/best-practices-for-using-webhooks'],
    frameworks: { iso27001: ['8.21', '8.24'] },
  }),
];
