import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const M = (d: Def): CheckMeta => ({ ...d, provider: 'm365' });

export const m365Checks: CheckMeta[] = [
  M({
    id: 'm365.mfa-all-users',
    domain: 'identity',
    title: 'MFA enforced for all users',
    description: 'Security Defaults or an enabled Conditional Access policy must require MFA for all users on all cloud apps, without narrowing conditions (locations, platforms, risk) and with exclusions limited to at most 2 break-glass accounts.',
    severity: 'critical',
    effort: 'medium',
    remediation: 'Enable a Conditional Access policy "Require MFA for all users" (all cloud apps, exclude only emergency access accounts), or turn on Security Defaults for tenants without Entra ID P1.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-all-users-mfa-strength'],
    frameworks: { iso27001: ['8.5', '5.17'], cis: 'M365 CIS v4.0 5.2.2.2', nis2: 'Art. 21(2)(j)' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.legacy-auth',
    domain: 'identity',
    title: 'Legacy authentication blocked',
    description: 'Legacy protocols (POP, IMAP, SMTP AUTH, EAS basic) do not support MFA and are used in password spraying. An enabled policy must block Exchange ActiveSync and other clients for all users and all cloud apps.',
    severity: 'high',
    effort: 'low',
    remediation: 'Create a Conditional Access policy blocking "Exchange ActiveSync clients" and "Other clients" for all users, or turn on Security Defaults for tenants without Entra ID P1.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-block-legacy-authentication'],
    frameworks: { iso27001: ['8.5'], cis: 'M365 CIS v4.0 5.2.2.3' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.admin-mfa',
    domain: 'privileged',
    title: 'Phishing-resistant MFA for administrators',
    description: 'The 14 CIS administrative roles (Global, Privileged Role, Security, Exchange, SharePoint, Conditional Access, Helpdesk, Billing, User, Authentication, Privileged Authentication, Application, Cloud Application and Intune Administrator) should be covered by enforced Conditional Access requiring a phishing-resistant authentication strength (built-in or custom with only FIDO2, Windows Hello for Business or certificate-based MFA).',
    severity: 'high',
    effort: 'medium',
    remediation: 'Create a Conditional Access policy targeting directory roles that requires the "Phishing-resistant MFA" authentication strength. Tenants without Entra ID P1 should at least turn on Security Defaults.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-admin-phish-resistant-mfa'],
    frameworks: { iso27001: ['8.5', '8.2'], cis: 'M365 CIS v4.0 5.2.2.1, 5.2.2.5' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.global-admin-count',
    domain: 'privileged',
    title: 'Between 2 and 4 Global Administrators',
    description: 'Too many Global Administrators increase exposure; fewer than two risks lock-out. Counts enabled active and PIM-eligible holders, including members of role-assignable groups.',
    severity: 'high',
    effort: 'low',
    remediation: 'Reduce Global Administrators to 2-4 (including emergency access accounts) and delegate least-privileged roles instead.',
    references: ['https://learn.microsoft.com/entra/identity/role-based-access-control/best-practices'],
    frameworks: { iso27001: ['8.2', '5.18'], cis: 'M365 CIS v4.0 1.1.3' },
    requires: 'RoleManagement.Read.Directory',
  }),
  M({
    id: 'm365.admins-cloud-only',
    domain: 'privileged',
    title: 'Privileged accounts are cloud-only',
    description: 'Synchronised on-premises accounts in privileged roles (active or PIM-eligible, directly or through role-assignable groups) allow an AD compromise to pivot to the cloud tenant.',
    severity: 'medium',
    effort: 'medium',
    remediation: 'Use dedicated cloud-only accounts for Entra ID administrative roles.',
    references: ['https://learn.microsoft.com/entra/architecture/protect-m365-from-on-premises-attacks'],
    frameworks: { iso27001: ['8.2'], cis: 'M365 CIS v4.0 1.1.1' },
    requires: 'RoleManagement.Read.Directory, User.Read.All',
  }),
  M({
    id: 'm365.mfa-registration',
    domain: 'identity',
    title: 'Users registered for MFA',
    description: 'Share of enabled member users with a registered MFA method.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Run an MFA registration campaign (Authentication methods > Registration campaign) and follow up on remaining users.',
    references: ['https://learn.microsoft.com/entra/identity/authentication/how-to-mfa-registration-campaign'],
    frameworks: { iso27001: ['8.5', '5.17'], cis: 'M365 CIS v4.0 5.2.3.4' },
    requires: 'AuditLog.Read.All (Entra ID P1)',
  }),
  M({
    id: 'm365.user-consent',
    domain: 'governance',
    title: 'User consent to applications restricted',
    description: 'Unrestricted user consent enables illicit consent grant (OAuth phishing) attacks.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Allow user consent only for verified publishers and low-impact permissions, or disable it and enable the admin consent workflow.',
    references: ['https://learn.microsoft.com/entra/identity/enterprise-apps/configure-user-consent'],
    frameworks: { iso27001: ['5.15', '8.2', '5.23'], cis: 'M365 CIS v4.0 5.1.5.1' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.user-app-registration',
    domain: 'governance',
    title: 'Users cannot register applications',
    description: 'Default users being able to create app registrations increases shadow IT and persistence options.',
    severity: 'low',
    effort: 'low',
    remediation: 'Set "Users can register applications" to No and assign Application Developer to those who need it.',
    references: ['https://learn.microsoft.com/entra/identity/role-based-access-control/delegate-app-roles'],
    frameworks: { iso27001: ['5.15', '8.9'], cis: 'M365 CIS v4.0 5.1.2.2' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.guest-invites',
    domain: 'identity',
    title: 'Guest invitations restricted',
    description: 'Allowing everyone (including guests) to invite external users weakens control over who has access.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Restrict guest invitations to admins and users in the Guest Inviter role.',
    references: ['https://learn.microsoft.com/entra/external-id/external-collaboration-settings-configure'],
    frameworks: { iso27001: ['5.15'], cis: 'M365 CIS v4.0 5.1.6.3' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.guest-access',
    domain: 'identity',
    title: 'Guest directory access restricted',
    description: 'Guests should not be able to enumerate the full directory.',
    severity: 'low',
    effort: 'low',
    remediation: 'Set guest user access to "Guest user access is restricted to properties and memberships of their own directory objects".',
    references: ['https://learn.microsoft.com/entra/identity/users/users-restrict-guest-permissions'],
    frameworks: { iso27001: ['8.3'], cis: 'M365 CIS v4.0 5.1.6.2' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.stale-accounts',
    domain: 'identity',
    title: 'No stale enabled accounts (90+ days)',
    description: 'Enabled accounts without a successful sign-in (lastSuccessfulSignInDateTime) for 90 days are often leavers that were never offboarded.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Disable stale accounts and implement periodic access reviews or a lifecycle workflow.',
    references: ['https://learn.microsoft.com/entra/identity/monitoring-health/howto-manage-inactive-user-accounts'],
    frameworks: { iso27001: ['5.18', '5.16'] },
    requires: 'AuditLog.Read.All (Entra ID P1)',
  }),
  M({
    id: 'm365.risky-app-permissions',
    domain: 'privileged',
    title: 'No over-privileged application permissions',
    description: 'Applications holding Tier-0 Graph permissions (RoleManagement.ReadWrite.Directory, AppRoleAssignment.ReadWrite.All, Application.ReadWrite.All, Directory.ReadWrite.All) can take over the tenant and always fail. Tenant-wide write permissions, tenant-wide read access to content (Mail.Read, Files.Read.All, Sites.Read.All) and delegated grants consented for all users are also reported.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Review each listed application, remove permissions not needed and prefer resource-scoped permissions (e.g. RBAC for Applications in Exchange).',
    references: ['https://learn.microsoft.com/entra/identity/enterprise-apps/manage-application-permissions'],
    frameworks: { iso27001: ['8.2', '5.19'] },
    requires: 'Application.Read.All, Directory.Read.All',
  }),
  M({
    id: 'm365.pim',
    domain: 'privileged',
    title: 'Privileged Identity Management in use',
    description: 'Just-in-time role activation reduces standing privileged access. Compares permanent active assignments of privileged roles with PIM-eligible assignments; more than 2 permanent Global Administrators (break-glass) fail.',
    severity: 'medium',
    effort: 'medium',
    remediation: 'Convert permanent privileged role assignments into PIM eligible assignments with approval and MFA on activation.',
    references: ['https://learn.microsoft.com/entra/id-governance/privileged-identity-management/pim-configure'],
    frameworks: { iso27001: ['8.2'], cis: 'M365 CIS v4.0 5.3.1' },
    requires: 'RoleManagement.Read.Directory (Entra ID P2)',
  }),
  M({
    id: 'm365.risk-policies',
    domain: 'identity',
    title: 'Sign-in and user risk policies',
    description: 'Identity Protection risk-based Conditional Access must cover both sign-in risk and user risk (including high) with a grant control, for all users and all cloud apps.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Create Conditional Access policies requiring MFA for medium+ sign-in risk and password change for high user risk.',
    references: ['https://learn.microsoft.com/entra/id-protection/howto-identity-protection-configure-risk-policies'],
    frameworks: { iso27001: ['8.5', '8.16'], cis: 'M365 CIS v4.0 5.2.2.6, 5.2.2.7' },
    requires: 'Policy.Read.All (Entra ID P2)',
  }),
  M({
    id: 'm365.device-compliance',
    domain: 'identity',
    title: 'Access requires managed or compliant devices',
    description: 'Device-based Conditional Access prevents access to corporate data from unmanaged devices.',
    severity: 'medium',
    effort: 'high',
    remediation: 'Require compliant or hybrid-joined devices for access to Microsoft 365 and enrol devices in Intune.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-all-users-device-compliance'],
    frameworks: { iso27001: ['8.1', '6.7'] },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.weak-auth-methods',
    domain: 'identity',
    title: 'Weak MFA methods (SMS / voice) disabled',
    description: 'SMS and voice calls are vulnerable to SIM swapping and interception. Until the authentication methods policy migration is complete, the legacy MFA and SSPR policies can still allow them.',
    severity: 'low',
    effort: 'low',
    remediation: 'Disable SMS and voice call in the Authentication methods policy after migrating users to Microsoft Authenticator or passkeys.',
    references: ['https://learn.microsoft.com/entra/identity/authentication/concept-authentication-methods-manage'],
    frameworks: { iso27001: ['8.5'], cis: 'M365 CIS v4.0 5.2.3.5' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.email-auth',
    domain: 'network',
    title: 'SPF, DKIM and DMARC enforced on mail domains',
    description: 'Verified mail domains should publish exactly one SPF record within the 10-lookup limit, DKIM for Exchange Online (selector1/selector2 CNAMEs) and an enforcing DMARC policy (quarantine/reject, pct=100, no sp=none). Subdomains without their own record inherit the organisational domain policy.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Publish a single SPF record ending in -all or ~all (flatten includes when above 10 lookups), enable DKIM signing in Microsoft Defender and publish the selector CNAMEs, and move DMARC to p=quarantine or p=reject with pct=100 after monitoring reports.',
    references: ['https://learn.microsoft.com/defender-office-365/email-authentication-dmarc-configure'],
    frameworks: { iso27001: ['5.14', '8.21'], cis: 'M365 CIS v4.0 2.1.8, 2.1.9, 2.1.10' },
    requires: 'Domain.Read.All',
  }),
  M({
    id: 'm365.secure-score',
    domain: 'governance',
    title: 'Microsoft Secure Score',
    description: 'Secure Score summarises the tenant posture against Microsoft recommendations. The evidence lists the controls with the largest gaps.',
    severity: 'low',
    effort: 'medium',
    remediation: 'Review the Secure Score improvement actions and plan the high-impact items.',
    references: ['https://learn.microsoft.com/defender-xdr/microsoft-secure-score'],
    frameworks: { iso27001: ['8.9'] },
    requires: 'SecurityEvents.Read.All',
  }),
  M({
    id: 'm365.device-code-flow',
    domain: 'identity',
    title: 'Device code flow blocked',
    description: 'The device code flow is abused in device code phishing to obtain tokens for a victim. An enabled Conditional Access policy should block it (authentication flows condition) for all users and all cloud apps.',
    severity: 'high',
    effort: 'low',
    remediation: 'Create a Conditional Access policy for all users and all cloud apps with the condition Authentication flows > Device code flow and grant Block access; exclude only break-glass accounts and, if needed, a group of meeting-room devices.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-block-authentication-flows'],
    frameworks: { iso27001: ['8.5'], cis: 'M365 CIS v4.0 5.2.2.12' },
    requires: 'Policy.Read.All (Entra ID P1)',
  }),
  M({
    id: 'm365.admin-session-controls',
    domain: 'privileged',
    title: 'Session controls for administrators',
    description: 'Administrator sessions should re-authenticate at least every 4 hours and browser sessions should not persist, limiting the value of stolen session cookies.',
    severity: 'medium',
    effort: 'low',
    remediation: 'Create a Conditional Access policy for the administrator roles and all cloud apps with session controls Sign-in frequency (4 hours or less) and Persistent browser session set to Never persistent.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/concept-session-lifetime'],
    frameworks: { iso27001: ['8.5', '8.2'], cis: 'M365 CIS v4.0 5.2.2.4' },
    requires: 'Policy.Read.All (Entra ID P1)',
  }),
  M({
    id: 'm365.authenticator-number-matching',
    domain: 'identity',
    title: 'Authenticator number matching and context',
    description: 'Microsoft Authenticator push notifications should require number matching and show the application name and geographic location to all users, to resist MFA fatigue attacks.',
    severity: 'medium',
    effort: 'low',
    remediation: 'In Authentication methods > Microsoft Authenticator > Configure, enable "Show application name" and "Show geographic location" for all users (number matching is enforced for push notifications).',
    references: ['https://learn.microsoft.com/entra/identity/authentication/how-to-mfa-additional-context'],
    frameworks: { iso27001: ['8.5'], cis: 'M365 CIS v4.0 5.2.3.1' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.app-credentials',
    domain: 'privileged',
    title: 'No long-lived application secrets',
    description: 'Client secrets valid for more than a year, expired credentials left on applications and secrets on multi-tenant apps with high-impact permissions widen the window for credential theft.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Replace client secrets with certificates or managed identities / workload identity federation, limit secret lifetime to 12 months or less (app management policy), and remove expired credentials.',
    references: ['https://learn.microsoft.com/entra/identity/enterprise-apps/tenant-restrict-app-management-policy', 'https://learn.microsoft.com/entra/workload-id/workload-identity-federation'],
    frameworks: { iso27001: ['5.17', '8.2'] },
    requires: 'Application.Read.All',
  }),
  M({
    id: 'm365.privileged-guests',
    domain: 'privileged',
    title: 'No guests or service principals in privileged roles',
    description: 'Guest accounts and service principals holding privileged directory roles (active or PIM-eligible) are outside normal joiner/leaver and MFA controls.',
    severity: 'high',
    effort: 'medium',
    remediation: 'Remove privileged roles from guests (use member accounts in this tenant instead) and replace directory roles on service principals with least-privileged application permissions.',
    references: ['https://learn.microsoft.com/entra/identity/role-based-access-control/best-practices'],
    frameworks: { iso27001: ['8.2', '5.18'] },
    requires: 'RoleManagement.Read.Directory',
  }),
];
