import type { CheckMeta } from '../types.js';

type Def = Omit<CheckMeta, 'provider'>;
const M = (d: Def): CheckMeta => ({ ...d, provider: 'm365' });

export const m365Checks: CheckMeta[] = [
  M({
    id: 'm365.mfa-all-users',
    domain: 'identity',
    title: 'MFA enforced for all users',
    description: 'Security Defaults or an enabled Conditional Access policy must require MFA for all users on all cloud apps.',
    severity: 'critical',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Enable a Conditional Access policy "Require MFA for all users" (all cloud apps, exclude only emergency access accounts), or turn on Security Defaults for tenants without Entra ID P1.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-all-users-mfa-strength'],
    frameworks: { iso27001: ['8.5', '5.17'], cis: 'M365 CIS 5.2.2.2', nis2: 'Art. 21(2)(j)' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.legacy-auth',
    domain: 'identity',
    title: 'Legacy authentication blocked',
    description: 'Legacy protocols (POP, IMAP, SMTP AUTH, EAS basic) do not support MFA and are used in password spraying.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Create a Conditional Access policy blocking "Exchange ActiveSync clients" and "Other clients" for all users, or turn on Security Defaults for tenants without Entra ID P1.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-block-legacy-authentication'],
    frameworks: { iso27001: ['8.5'], cis: 'M365 CIS 5.2.2.3' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.admin-mfa',
    domain: 'privileged',
    title: 'Phishing-resistant MFA for administrators',
    description: 'Administrative roles should be covered by Conditional Access requiring (phishing-resistant) MFA.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Create a Conditional Access policy targeting directory roles that requires the "Phishing-resistant MFA" authentication strength. Tenants without Entra ID P1 should at least turn on Security Defaults.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-admin-phish-resistant-mfa'],
    frameworks: { iso27001: ['8.2', '8.5'], cis: 'M365 CIS 5.2.2.1' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.global-admin-count',
    domain: 'privileged',
    title: 'Between 2 and 4 Global Administrators',
    description: 'Too many Global Administrators increase exposure; fewer than two risks lock-out.',
    severity: 'high',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Reduce Global Administrators to 2-4 (including emergency access accounts) and delegate least-privileged roles instead.',
    references: ['https://learn.microsoft.com/entra/identity/role-based-access-control/best-practices'],
    frameworks: { iso27001: ['8.2', '5.18'], cis: 'M365 CIS 1.1.3' },
    requires: 'RoleManagement.Read.Directory',
  }),
  M({
    id: 'm365.admins-cloud-only',
    domain: 'privileged',
    title: 'Privileged accounts are cloud-only',
    description: 'Synchronised on-premises accounts in privileged roles allow an AD compromise to pivot to the cloud tenant.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'medium',
    remediation: 'Use dedicated cloud-only accounts for Entra ID administrative roles.',
    references: ['https://learn.microsoft.com/entra/architecture/protect-m365-from-on-premises-attacks'],
    frameworks: { iso27001: ['8.2'], cis: 'M365 CIS 1.1.1' },
    requires: 'RoleManagement.Read.Directory, User.Read.All',
  }),
  M({
    id: 'm365.mfa-registration',
    domain: 'identity',
    title: 'Users registered for MFA',
    description: 'Share of enabled member users with a registered MFA method.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Run an MFA registration campaign (Authentication methods > Registration campaign) and follow up on remaining users.',
    references: ['https://learn.microsoft.com/entra/identity/authentication/how-to-mfa-registration-campaign'],
    frameworks: { iso27001: ['8.5', '5.17'] },
    requires: 'AuditLog.Read.All (Entra ID P1)',
  }),
  M({
    id: 'm365.user-consent',
    domain: 'governance',
    title: 'User consent to applications restricted',
    description: 'Unrestricted user consent enables illicit consent grant (OAuth phishing) attacks.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Allow user consent only for verified publishers and low-impact permissions, or disable it and enable the admin consent workflow.',
    references: ['https://learn.microsoft.com/entra/identity/enterprise-apps/configure-user-consent'],
    frameworks: { iso27001: ['5.19', '5.23'], cis: 'M365 CIS 5.1.5.1' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.user-app-registration',
    domain: 'governance',
    title: 'Users cannot register applications',
    description: 'Default users being able to create app registrations increases shadow IT and persistence options.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Set "Users can register applications" to No and assign Application Developer to those who need it.',
    references: ['https://learn.microsoft.com/entra/identity/role-based-access-control/delegate-app-roles'],
    frameworks: { iso27001: ['5.15', '8.9'], cis: 'M365 CIS 5.1.2.2' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.guest-invites',
    domain: 'identity',
    title: 'Guest invitations restricted',
    description: 'Allowing everyone (including guests) to invite external users weakens control over who has access.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Restrict guest invitations to admins and users in the Guest Inviter role.',
    references: ['https://learn.microsoft.com/entra/external-id/external-collaboration-settings-configure'],
    frameworks: { iso27001: ['5.15', '5.19'], cis: 'M365 CIS 5.1.6.2' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.guest-access',
    domain: 'identity',
    title: 'Guest directory access restricted',
    description: 'Guests should not be able to enumerate the full directory.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Set guest user access to "Guest user access is restricted to properties and memberships of their own directory objects".',
    references: ['https://learn.microsoft.com/entra/identity/users/users-restrict-guest-permissions'],
    frameworks: { iso27001: ['8.3'], cis: 'M365 CIS 5.1.6.3' },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.stale-accounts',
    domain: 'identity',
    title: 'No stale enabled accounts (90+ days)',
    description: 'Enabled accounts without sign-in for 90 days are often leavers that were never offboarded.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Disable stale accounts and implement periodic access reviews or a lifecycle workflow.',
    references: ['https://learn.microsoft.com/entra/identity/monitoring-health/howto-manage-inactive-user-accounts'],
    frameworks: { iso27001: ['5.18', '5.16'] },
    requires: 'AuditLog.Read.All (Entra ID P1)',
  }),
  M({
    id: 'm365.risky-app-permissions',
    domain: 'privileged',
    title: 'No over-privileged application permissions',
    description: 'Applications holding tenant-wide write permissions (e.g. Directory.ReadWrite.All, Mail.ReadWrite) are high-value targets.',
    severity: 'high',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Review each listed application, remove permissions not needed and prefer resource-scoped permissions (e.g. RBAC for Applications in Exchange).',
    references: ['https://learn.microsoft.com/entra/identity/enterprise-apps/manage-application-permissions'],
    frameworks: { iso27001: ['8.2', '5.19'] },
    requires: 'Application.Read.All',
  }),
  M({
    id: 'm365.pim',
    domain: 'privileged',
    title: 'Privileged Identity Management in use',
    description: 'Just-in-time role activation reduces standing privileged access.',
    severity: 'medium',
    minRisk: 'medium',
    effort: 'medium',
    remediation: 'Convert permanent privileged role assignments into PIM eligible assignments with approval and MFA on activation.',
    references: ['https://learn.microsoft.com/entra/id-governance/privileged-identity-management/pim-configure'],
    frameworks: { iso27001: ['8.2'] },
    requires: 'RoleManagement.Read.Directory (Entra ID P2)',
  }),
  M({
    id: 'm365.risk-policies',
    domain: 'identity',
    title: 'Sign-in and user risk policies',
    description: 'Identity Protection risk-based Conditional Access blocks or challenges risky sign-ins.',
    severity: 'medium',
    minRisk: 'high',
    effort: 'low',
    remediation: 'Create Conditional Access policies requiring MFA for medium+ sign-in risk and password change for high user risk.',
    references: ['https://learn.microsoft.com/entra/id-protection/howto-identity-protection-configure-risk-policies'],
    frameworks: { iso27001: ['8.16', '8.5'] },
    requires: 'Policy.Read.All (Entra ID P2)',
  }),
  M({
    id: 'm365.device-compliance',
    domain: 'identity',
    title: 'Access requires managed or compliant devices',
    description: 'Device-based Conditional Access prevents access to corporate data from unmanaged devices.',
    severity: 'medium',
    minRisk: 'high',
    effort: 'high',
    remediation: 'Require compliant or hybrid-joined devices for access to Microsoft 365 and enrol devices in Intune.',
    references: ['https://learn.microsoft.com/entra/identity/conditional-access/policy-all-users-device-compliance'],
    frameworks: { iso27001: ['8.1', '6.7'] },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.weak-auth-methods',
    domain: 'identity',
    title: 'Weak MFA methods (SMS / voice) disabled',
    description: 'SMS and voice calls are vulnerable to SIM swapping and interception.',
    severity: 'low',
    minRisk: 'medium',
    effort: 'low',
    remediation: 'Disable SMS and voice call in the Authentication methods policy after migrating users to Microsoft Authenticator or passkeys.',
    references: ['https://learn.microsoft.com/entra/identity/authentication/concept-authentication-methods-manage'],
    frameworks: { iso27001: ['8.5'] },
    requires: 'Policy.Read.All',
  }),
  M({
    id: 'm365.email-auth',
    domain: 'data',
    title: 'SPF and DMARC enforced on mail domains',
    description: 'Verified domains should publish SPF and an enforcing DMARC policy (quarantine/reject) to prevent spoofing.',
    severity: 'medium',
    minRisk: 'low',
    effort: 'low',
    remediation: 'Publish an SPF record ending in -all or ~all and move DMARC to p=quarantine or p=reject after monitoring reports.',
    references: ['https://learn.microsoft.com/defender-office-365/email-authentication-dmarc-configure'],
    frameworks: { iso27001: ['5.14', '8.21'], cis: 'M365 CIS 2.1.10' },
    requires: 'Domain.Read.All',
  }),
  M({
    id: 'm365.secure-score',
    domain: 'governance',
    title: 'Microsoft Secure Score',
    description: 'Secure Score summarises the tenant posture against Microsoft recommendations.',
    severity: 'low',
    minRisk: 'low',
    effort: 'medium',
    remediation: 'Review the Secure Score improvement actions and plan the high-impact items.',
    references: ['https://learn.microsoft.com/defender-xdr/microsoft-secure-score'],
    frameworks: { iso27001: ['8.9', '8.8'] },
    requires: 'SecurityEvents.Read.All',
  }),
];
